### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by mugavri** [tdlight-team/tdlight-telegram-bot-api#11] opened 2020-11-24 00:45 UTC
i get building error on windows 10

**error message:**
`C:\test\tdlight-telegram-bot-api\td\td\generate\tl-parser\tl-parser.c(43,10): fatal error C1083: Cannot open include fi
le: 'zlib.h': No such file or directory [C:\test\tdlight-telegram-bot-api\td\td\generate\tl-parser\contrib\vs\tl-parser
.vcxproj] [C:\test\tdlight-telegram-bot-api\build\td\td\generate\build_tl_parser.vcxproj]`

on run 
`cmake --build . --target install --config Release` 
command

**Comment by Cavallium** [comment] 2020-11-24 00:57
Do this error appear also using the official telegram bot api?

**Comment by mugavri** [comment] 2020-11-24 12:30
> Do this error appear also using the official telegram bot api?

no

**Comment by giuseppeM99** [comment] 2020-11-24 14:12
seems that you need to install zlib, follow the instruction on https://tdlib.github.io/td/build.html?language=Other
from what i see you should execute the following
```
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
./bootstrap-vcpkg.bat
./vcpkg.exe install openssl:x64-windows zlib:x64-windows
cd ..
```
before building the bot-api

**Comment by mugavri** [comment] 2020-11-24 16:50
Of course I've done this before

**Comment by Cavallium** [comment] 2020-11-24 17:02
Oh now I see that the problem is related to tl-parser. You must add the directory vcpkg/installed/x64-windows/include into PATH before building

**Comment by mugavri** [comment] 2020-11-24 17:21
thanks i wiil try

**Comment by Cavallium** [comment] 2020-11-25 10:39
@mugavri Did it work?

**Comment by giuseppeM99** [comment] 2020-11-27 11:50
Is this solved?

**Comment by Cavallium** [comment] 2020-11-28 09:34
I'm closing the issue since the build with the correct path should work, and who opened the issue isn't replying anymore

**Closed by Cavallium** 2020-11-28 09:34 UTC
Labels: help wanted
